# Generated by Django 4.2.3 on 2023-09-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplan_stripe_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='pending_downgrade_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
