# Generated by Django 4.2.3 on 2023-09-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_remove_subscriptionplan_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='downloads_this_month',
            field=models.IntegerField(default=0),
        ),
    ]
