# Generated by Django 4.2.3 on 2023-09-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordUpp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='name',
            field=models.CharField(default='Untitled Canvas', max_length=100),
        ),
    ]
