# Generated by Django 4.2.3 on 2023-09-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordUpp', '0002_canvas_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='word_objects',
            field=models.JSONField(default=list),
        ),
    ]
