# Generated by Django 4.2.3 on 2023-09-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordUpp', '0004_canvas_horizontal_slider_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='horizontal_slider_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='vertical_slider_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
