# Generated by Django 4.2.3 on 2023-09-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasstate',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
